---
- hosts: localhost
  vars_files:
    - vars/main.yml
  tasks:
  - name: Create new Digital Ocean VM ('Droplet')
    register: my_vm
    digital_ocean: >
      state=present
      command=droplet
      name={{ hostname }}
      size_id=66
      region_id=5
      image_id=3240036
      ssh_key_ids=95607,110709
      wait_timeout=500
      unique_name=yes

  - name: Print info about VM
    debug: >
      msg="ID is {{ my_vm.droplet.id }} IP is {{ my_vm.droplet.ip_address }}"

  - name: Add new droplet to host group
    local_action: add_host hostname={{ my_vm.droplet.ip_address }} groups=launched

  - name: Wait for SSH to come up
    local_action: wait_for host={{ my_vm.droplet.ip_address }} port=22 timeout=320 state=started

- hosts: launched
  remote_user: root
  vars_files:
    - vars/main.yml
  roles:
    - ubuntu_bootstrap
